import { useRoute } from "wouter";
import { ArrowLeft, BadgeCheck, Printer } from "lucide-react";
import { trpc } from "@/lib/trpc";

export default function CertificatePrint() {
  const [, params] = useRoute("/certificate/print/:code");
  const code = params?.code ?? "";
  const verification = trpc.learning.verifyCertificate.useQuery({ certificateCode: code }, { enabled: Boolean(code) });

  if (verification.isLoading) return <main className="grid min-h-screen place-items-center bg-[#f2f4f3] text-slate-700"><p className="font-mono-ui text-sm">수료 기록을 확인하고 있습니다.</p></main>;
  if (!verification.data) return <main className="grid min-h-screen place-items-center bg-[#f2f4f3] p-6 text-center text-slate-800"><div><p className="font-mono-ui text-xs tracking-[0.16em] text-teal-700">CERTIFICATE VERIFICATION</p><h1 className="mt-3 text-2xl font-semibold">확인할 수 없는 인증번호입니다.</h1><p className="mt-2 text-sm text-slate-500">인증번호를 다시 확인하거나 수료 기록 화면으로 돌아가 주세요.</p><a href="/certificate" className="mt-6 inline-flex rounded-md border border-teal-700/30 px-4 py-2 text-sm text-teal-800">수료 기록으로 돌아가기</a></div></main>;

  const certificate = verification.data;
  return <main className="min-h-screen bg-[#f2f4f3] p-4 text-slate-800 sm:p-10"><div className="no-print mx-auto mb-6 flex max-w-4xl justify-between"><a href="/certificate" className="inline-flex items-center gap-2 text-sm text-slate-600 hover:text-teal-800"><ArrowLeft className="h-4 w-4" />수료 기록</a><button onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-md bg-[#0c3437] px-4 py-2 text-sm font-medium text-white"><Printer className="h-4 w-4" />인쇄</button></div><section className="certificate-sheet mx-auto max-w-4xl border border-[#99aaa7] bg-[#fbfcfb] p-8 shadow-2xl shadow-slate-900/10 sm:p-14"><div className="flex items-start justify-between border-b border-[#a5b5b2] pb-8"><div><p className="font-mono-ui text-[10px] tracking-[0.24em] text-teal-800">HACK GUIDANCE</p><h1 className="mt-2 text-2xl font-semibold tracking-[-0.03em]">웹 보안 기초 과정 수료증</h1></div><BadgeCheck className="h-9 w-9 text-teal-700" /></div><div className="py-12 text-center"><p className="text-sm text-slate-500">본 수료증은</p><p className="mt-4 text-3xl font-semibold tracking-[-0.03em] sm:text-4xl">{certificate.learnerName ?? "학습자"}</p><p className="mt-5 text-sm leading-7 text-slate-600">님이 Hack Guidance의 웹 보안 기초 과정을 이수하였음을 확인합니다.<br />본 과정은 안전한 분석 실습과 방어 기준 학습을 포함합니다.</p></div><div className="grid gap-px border border-[#c2cfcd] bg-[#c2cfcd] sm:grid-cols-3"><CertificateCell label="학습 문제" value={`${certificate.completedModules} / 50`} /><CertificateCell label="레벨 평가" value={`${certificate.passedAssessments} / 5`} /><CertificateCell label="방어 기준" value={`${certificate.defenseReviewCount} / 50`} /></div><div className="mt-10 flex flex-wrap items-end justify-between gap-5 text-sm"><div><p className="font-mono-ui text-[10px] tracking-[0.16em] text-slate-500">ISSUED ON</p><p className="mt-2">{new Date(certificate.issuedAt).toLocaleDateString("ko-KR")}</p></div><div className="text-right"><p className="font-mono-ui text-[10px] tracking-[0.16em] text-slate-500">VERIFICATION CODE</p><p className="mt-2 font-mono-ui text-sm tracking-[0.08em] text-teal-800">{certificate.certificateCode}</p></div></div><p className="mt-9 border-t border-[#d8e0de] pt-5 text-xs leading-5 text-slate-500">이 문서는 Hack Guidance가 제공하는 웹 보안 기초 학습 과정의 완료 기록입니다. 국가 공인 또는 전문 자격증이 아닙니다.</p></section><style>{`@media print { .no-print { display: none !important; } body { background: white !important; } .certificate-sheet { box-shadow: none !important; max-width: none !important; } }`}</style></main>;
}

function CertificateCell({ label, value }: { label: string; value: string }) { return <div className="bg-[#fbfcfb] p-5 text-center"><p className="font-mono-ui text-[9px] tracking-[0.13em] text-slate-500">{label}</p><p className="mt-2 text-lg font-semibold text-[#163c3d]">{value}</p></div>; }
