import { useLocation } from "wouter";
import { ArrowRight, Flag, ScrollText, Trophy } from "lucide-react";
import { usePlatformAuth } from "@/hooks/usePlatformAuth";
import { useLearningDashboard } from "@/hooks/useLearningApi";
import { ConsoleNav } from "@/components/ConsoleNav";

export default function Home() {
  const [, setLocation] = useLocation();
  const { isAuthenticated } = usePlatformAuth();
  const dashboard = useLearningDashboard({ enabled: isAuthenticated, retry: false });
  const solved = dashboard.data?.completedIds.length ?? 0;
  return <div className="hacknet-shell min-h-screen bg-[#060b0d] text-[#e7f2ef]"><ConsoleNav /><main className="relative mx-auto max-w-[1180px] px-4 py-10 lg:px-6 lg:py-16"><section className="hnet-panel relative overflow-hidden border border-[#34535a] px-6 py-10 sm:px-10 sm:py-14"><div className="hnet-node-map absolute inset-0 opacity-50" /><div className="relative max-w-2xl"><p className="font-mono-ui text-[10px] tracking-[0.2em] text-teal-300">CHALLENGE GRID // 50 OPEN NODES</p><h1 className="mt-4 text-4xl font-semibold tracking-[-0.05em] text-white sm:text-5xl">문제를 풀고<br />플래그를 제출하세요.</h1><p className="mt-5 max-w-xl text-sm leading-7 text-slate-300">Hack Guidance는 보안 단서를 분석해 플래그를 확보하는 문제 풀이 보드입니다. 모든 문제는 처음부터 열려 있으며, 막히면 최대 세 개의 단서를 확인할 수 있습니다.</p><button onClick={() => setLocation("/problems")} className="mt-8 inline-flex items-center gap-2 bg-teal-300 px-4 py-3 text-sm font-semibold text-[#092024] transition hover:bg-teal-200">문제 목록 열기 <ArrowRight className="h-4 w-4" /></button></div></section><section className="mt-6 grid gap-4 sm:grid-cols-3"><StatusCard icon={<Flag className="h-4 w-4" />} label="SOLVED NODES" value={`${solved} / 50`} action="문제 보기" onClick={() => setLocation("/problems")} /><StatusCard icon={<ScrollText className="h-4 w-4" />} label="SOLVE LOG" value="개인 기록" action="기록 보기" onClick={() => setLocation("/records")} /><StatusCard icon={<Trophy className="h-4 w-4" />} label="PUBLIC RANKING" value="공개 순위" action="랭킹 보기" onClick={() => setLocation("/ranking")} /></section><section className="mt-10 grid gap-4 border-t border-[#294247] pt-8 sm:grid-cols-3"><Guide number="01" title="문제 선택" text="문제 메뉴에서 원하는 노드와 구역을 선택합니다." /><Guide number="02" title="단서 분석" text="페이지·요청·응답에 남은 증거를 확인합니다." /><Guide number="03" title="플래그 제출" text="확보한 HG{...} 값을 제출해 해결 기록을 남깁니다." /></section></main></div>;
}

function StatusCard({ icon, label, value, action, onClick }: { icon: React.ReactNode; label: string; value: string; action: string; onClick: () => void }) { return <section className="border border-[#294247] bg-[#101b1e] p-5"><div className="flex items-center gap-2 text-teal-300">{icon}<span className="font-mono-ui text-[10px] tracking-[0.14em] text-slate-500">{label}</span></div><p className="mt-4 text-xl font-semibold text-white">{value}</p><button onClick={onClick} className="mt-5 text-xs text-teal-200 hover:text-teal-100">{action} →</button></section>; }
function Guide({ number, title, text }: { number: string; title: string; text: string }) { return <div><p className="font-mono-ui text-xs text-teal-300">{number}</p><h2 className="mt-2 text-sm font-semibold text-white">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>; }
