import { useLocation } from "wouter";
import { ArrowRight, Flag, ScrollText, Trophy } from "lucide-react";
import { usePlatformAuth } from "@/hooks/usePlatformAuth";
import { useLearningDashboard } from "@/hooks/useLearningApi";
import { ConsoleNav } from "@/components/ConsoleNav";

export default function Home() {
  const [, setLocation] = useLocation();
  const { isAuthenticated } = usePlatformAuth();
  const dashboard = useLearningDashboard({ enabled: isAuthenticated, retry: false });
  const solved = dashboard.data?.completedIds.length ?? 0;
  return <div className="hacknet-shell min-h-screen bg-[#060b0d] text-[#e7f2ef]"><ConsoleNav /><main className="relative mx-auto max-w-[1180px] px-4 py-10 lg:px-6 lg:py-16"><section className="hnet-panel relative overflow-hidden border border-[#34535a] px-6 py-10 sm:px-10 sm:py-14"><div className="hnet-node-map absolute inset-0 opacity-50" /><div className="relative max-w-2xl"><p className="font-mono-ui text-[10px] tracking-[0.2em] text-teal-300">CHALLENGE INVENTORY // RESET</p><h1 className="mt-4 text-4xl font-semibold tracking-[-0.05em] text-white sm:text-5xl">새 문제 공간을<br />준비하고 있습니다.</h1><p className="mt-5 max-w-xl text-sm leading-7 text-slate-300">기존 문제와 전용 타깃은 모두 초기화했습니다. 새로운 웹 보안 문제 구조는 설계를 다시 정리한 뒤 등록됩니다.</p><button onClick={() => setLocation("/problems")} className="mt-8 inline-flex items-center gap-2 bg-teal-300 px-4 py-3 text-sm font-semibold text-[#092024] transition hover:bg-teal-200">문제 상태 보기 <ArrowRight className="h-4 w-4" /></button></div></section><section className="mt-6 grid gap-4 sm:grid-cols-3"><StatusCard icon={<Flag className="h-4 w-4" />} label="ACTIVE CHALLENGES" value="0" action="문제 상태" onClick={() => setLocation("/problems")} /><StatusCard icon={<ScrollText className="h-4 w-4" />} label="ACCOUNT" value="개인 기록" action="기록 보기" onClick={() => setLocation("/records")} /><StatusCard icon={<Trophy className="h-4 w-4" />} label="PUBLIC RANKING" value="공개 순위" action="랭킹 보기" onClick={() => setLocation("/ranking")} /></section><section className="mt-10 grid gap-4 border-t border-[#294247] pt-8 sm:grid-cols-3"><Guide number="01" title="문제 설계" text="새 문제의 목표와 안전한 실습 경계를 다시 정의합니다." /><Guide number="02" title="시나리오 검토" text="타깃 서비스와 분석 흐름을 실제 문제 구조로 설계합니다." /><Guide number="03" title="등록 준비" text="검증된 문제만 새 인벤토리에 등록합니다." /></section></main></div>;
}

function StatusCard({ icon, label, value, action, onClick }: { icon: React.ReactNode; label: string; value: string; action: string; onClick: () => void }) { return <section className="border border-[#294247] bg-[#101b1e] p-5"><div className="flex items-center gap-2 text-teal-300">{icon}<span className="font-mono-ui text-[10px] tracking-[0.14em] text-slate-500">{label}</span></div><p className="mt-4 text-xl font-semibold text-white">{value}</p><button onClick={onClick} className="mt-5 text-xs text-teal-200 hover:text-teal-100">{action} →</button></section>; }
function Guide({ number, title, text }: { number: string; title: string; text: string }) { return <div><p className="font-mono-ui text-xs text-teal-300">{number}</p><h2 className="mt-2 text-sm font-semibold text-white">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>; }
