import { Crown, Trophy } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { ConsoleNav } from "@/components/ConsoleNav";

export default function Ranking() {
  const ranking = trpc.learning.ranking.useQuery();
  const rows = ranking.data ?? [];
  return <div className="hacknet-shell min-h-screen bg-[#060b0d] text-[#e7f2ef]"><ConsoleNav /><main className="mx-auto max-w-6xl px-4 py-10 sm:px-6"><p className="font-mono-ui text-[10px] tracking-[0.2em] text-teal-300">PUBLIC RANKING // SOLVED NODES</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.04em] text-white">공개 랭킹</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">해결한 문제 수를 우선으로 정렬하며, 같은 수라면 마지막 해결 기록이 빠른 분석자가 먼저 표시됩니다.</p><section className="hnet-panel mt-8 overflow-hidden border border-[#315057]"><div className="hidden grid-cols-[80px_minmax(0,1fr)_140px_180px] border-b border-[#294247] bg-[#0a1518] px-5 py-3 font-mono-ui text-[10px] tracking-[0.14em] text-slate-500 sm:grid"><span>RANK</span><span>OPERATOR</span><span>SOLVED</span><span>LAST SIGNAL</span></div>{ranking.isLoading ? <div className="p-8 text-sm text-slate-400">랭킹 신호를 수집하고 있습니다.</div> : rows.length === 0 ? <div className="p-8 text-center"><Trophy className="mx-auto h-7 w-7 text-teal-300" /><p className="mt-3 text-sm text-slate-300">아직 공개 랭킹에 기록된 해결자가 없습니다.</p></div> : <div className="divide-y divide-[#294247]">{rows.map((row, index) => <div key={row.userId} className="grid gap-2 px-5 py-4 sm:grid-cols-[80px_minmax(0,1fr)_140px_180px] sm:items-center"><span className={`font-mono-ui text-sm ${index === 0 ? "text-amber-200" : "text-slate-500"}`}>{index === 0 ? <Crown className="h-4 w-4" /> : String(index + 1).padStart(2, "0")}</span><span className="truncate text-sm font-medium text-slate-100">{row.name ?? "ANONYMOUS OPERATOR"}</span><span className="font-mono-ui text-sm text-teal-200">{row.solvedCount} / 50</span><span className="text-xs text-slate-500">{row.lastSolvedAt ? new Date(row.lastSolvedAt).toLocaleString("ko-KR") : "기록 없음"}</span></div>)}</div>}</section></main></div>;
}
