import { ArchiveX, BookCheck, CheckCircle2, Radio } from "lucide-react";
import { useLocation } from "wouter";
import { usePlatformAuth, startPlatformLogin } from "@/hooks/usePlatformAuth";
import { ConsoleNav } from "@/components/ConsoleNav";
import { useLearningRecords } from "@/hooks/useLearningApi";

type OperationRecord = { stage: number; hintCount: number; completedAt: string };

export default function Records() {
  const [, setLocation] = useLocation();
  const { isAuthenticated } = usePlatformAuth();
  const recordsQuery = useLearningRecords({ enabled: isAuthenticated, retry: false });
  const records = (recordsQuery.data ?? []) as OperationRecord[];
  if (!isAuthenticated) return <div className="hacknet-shell min-h-screen bg-[#060b0d] text-slate-100"><ConsoleNav /><main className="grid place-items-center p-6 pt-28 text-center"><div className="max-w-md"><BookCheck className="mx-auto h-8 w-8 text-teal-300" /><p className="mt-5 font-mono-ui text-[10px] tracking-[0.2em] text-teal-300">OPERATOR HISTORY</p><h1 className="mt-3 text-2xl font-semibold">개인 기록은 로그인 후 확인할 수 있습니다.</h1><p className="mt-3 text-sm leading-6 text-slate-400">BLACK TRACE에서 회수한 Stage 기록은 계정별로 이곳에 저장됩니다.</p><button onClick={startPlatformLogin} className="mt-6 bg-teal-300 px-4 py-2.5 text-sm font-semibold text-[#092024]">로그인</button></div></main></div>;
  if (recordsQuery.isLoading) return <div className="hacknet-shell min-h-screen bg-[#060b0d] text-[#e7f2ef]"><ConsoleNav /><main className="grid min-h-[calc(100vh-5rem)] place-items-center p-6 text-sm text-slate-400">회수 기록을 동기화하고 있습니다.</main></div>;
  if (records.length === 0) return <div className="hacknet-shell min-h-screen bg-[#060b0d] text-[#e7f2ef]"><ConsoleNav /><main className="grid min-h-[calc(100vh-5rem)] place-items-center p-6 text-center"><section className="max-w-md"><ArchiveX className="mx-auto h-9 w-9 text-slate-600" /><p className="mt-5 font-mono-ui text-[10px] tracking-[0.2em] text-slate-500">OPERATION HISTORY // EMPTY</p><h1 className="mt-3 text-2xl font-semibold">아직 회수한 TRACE가 없습니다.</h1><p className="mt-3 text-sm leading-6 text-slate-400">작전 보드에서 Stage를 완료하면 회수 기록이 이곳에 남습니다.</p><button onClick={() => setLocation("/black-trace")} className="mt-6 border border-teal-300/40 px-4 py-2 text-sm text-teal-100">작전 보드 열기</button></section></main></div>;
  return <div className="hacknet-shell min-h-screen bg-[#060b0d] text-[#e7f2ef]"><ConsoleNav /><main className="mx-auto max-w-5xl px-4 py-10 sm:px-6"><p className="font-mono-ui text-[10px] tracking-[0.2em] text-teal-300">OPERATION HISTORY // BLACK TRACE</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold tracking-[-0.04em] text-white">해결 기록</h1><p className="mt-2 text-sm text-slate-400">브라우저 분석으로 회수한 작전 노드 기록입니다.</p></div><p className="font-mono-ui text-sm text-teal-200">{records.length} / 10 NODES RECOVERED</p></div><section className="hnet-panel mt-8 overflow-hidden border border-[#315057]"><div className="hidden grid-cols-[110px_minmax(0,1fr)_130px_190px] border-b border-[#294247] bg-[#0a1518] px-5 py-3 font-mono-ui text-[10px] tracking-[0.14em] text-slate-500 sm:grid"><span>NODE</span><span>STATUS</span><span>INTEL USED</span><span>RECOVERED AT</span></div><div className="divide-y divide-[#294247]">{records.map(record => <div key={record.stage} className="grid gap-2 px-5 py-4 sm:grid-cols-[110px_minmax(0,1fr)_130px_190px] sm:items-center"><span className="font-mono-ui text-sm text-teal-200">STAGE {String(record.stage).padStart(2, "0")}</span><span className="inline-flex items-center gap-2 text-sm font-medium text-slate-100"><CheckCircle2 className="h-4 w-4 text-teal-300" />TRACE RECOVERED</span><span className="font-mono-ui text-xs text-slate-400">{record.hintCount} / 2</span><span className="inline-flex items-center gap-2 text-xs text-slate-500"><Radio className="h-3.5 w-3.5 text-teal-300" />{new Date(record.completedAt).toLocaleString("ko-KR")}</span></div>)}</div></section></main></div>;
}
