import { useLocation } from "wouter";
import { ArrowLeft, BookCheck, Check, CircleHelp, ShieldCheck } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { challengeById } from "@shared/learning";

export default function Records() {
  const [, setLocation] = useLocation();
  const { isAuthenticated } = useAuth();
  const records = trpc.learning.records.useQuery(undefined, { enabled: isAuthenticated, retry: false });
  if (!isAuthenticated) return <main className="hacknet-shell grid min-h-screen place-items-center bg-[#060b0d] p-6 text-center text-slate-100"><div className="max-w-md"><BookCheck className="mx-auto h-8 w-8 text-teal-300" /><p className="mt-5 font-mono-ui text-[10px] tracking-[0.2em] text-teal-300">SOLVE LOG</p><h1 className="mt-3 text-2xl font-semibold">해결 기록은 로그인 후 확인할 수 있습니다.</h1><p className="mt-3 text-sm leading-6 text-slate-400">문제별 해결 시각, 사용한 단서 수, 대응 노트 확인 상태를 개인 풀이 기록으로 제공합니다.</p><button onClick={startLogin} className="mt-6 bg-teal-300 px-4 py-2.5 text-sm font-semibold text-[#092024]">로그인하여 기록 확인</button></div></main>;
  const rows = records.data ?? [];
  return <div className="hacknet-shell min-h-screen bg-[#060b0d] text-[#e7f2ef]"><header className="hnet-header border-b border-[#294247]"><div className="mx-auto flex h-16 max-w-6xl items-center px-4 sm:px-6"><button onClick={() => setLocation("/")} className="inline-flex items-center gap-2 text-sm text-slate-300 transition hover:text-teal-100"><ArrowLeft className="h-4 w-4" />문제 보드</button></div></header><main className="mx-auto max-w-6xl px-4 py-10 sm:px-6"><p className="font-mono-ui text-[10px] tracking-[0.2em] text-teal-300">SOLVE LOG / OPERATOR HISTORY</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.04em] text-white">문제 해결 기록</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">해결한 문제와 사용한 단서, 대응 노트 확인 상태를 확인합니다. 단서 사용 여부는 해결 상태에 영향을 주지 않습니다.</p><div className="hnet-panel mt-8 overflow-hidden border border-[#315057]">{records.isLoading ? <div className="p-8 text-sm text-slate-400">해결 기록을 불러오는 중입니다.</div> : rows.length === 0 ? <div className="p-8 text-center"><p className="text-lg font-medium text-white">아직 해결한 문제가 없습니다.</p><p className="mt-2 text-sm text-slate-400">첫 번째 문제를 해결하면 풀이 로그가 여기에 표시됩니다.</p><button onClick={() => setLocation("/lab/1")} className="mt-5 border border-teal-300/40 px-3 py-2 text-xs text-teal-100">문제 #01 열기</button></div> : <div className="divide-y divide-[#294247]">{rows.map(row => { const challenge = challengeById(row.problemId); return <div key={row.problemId} className="grid gap-3 px-5 py-4 sm:grid-cols-[72px_minmax(0,1fr)_140px_120px] sm:items-center"><div><p className="font-mono-ui text-xs text-teal-200">#{String(row.problemId).padStart(2, "0")}</p><p className="mt-1 font-mono-ui text-[9px] text-slate-500">SECTOR {row.level}</p></div><div><p className="text-sm font-medium text-slate-100">{challenge?.title ?? "보안 문제"}</p><p className="mt-1 text-xs text-slate-500">해결: {row.completedAt ? new Date(row.completedAt).toLocaleString("ko-KR") : "기록 없음"}</p></div><div className="flex items-center gap-2 text-xs text-slate-400"><CircleHelp className="h-3.5 w-3.5 text-amber-200" />단서 {row.hintCount}/3</div><div className={`flex items-center gap-2 text-xs ${row.defenseReviewed ? "text-teal-100" : "text-slate-500"}`}>{row.defenseReviewed ? <Check className="h-3.5 w-3.5" /> : <ShieldCheck className="h-3.5 w-3.5" />}{row.defenseReviewed ? "대응 노트 확인" : "대응 노트 미확인"}</div></div>; })}</div>}</div></main></div>;
}
