export type BlackTraceStage = {
  id: number;
  /** Stable name for this node's puzzle, independent of where it sits in the order.
   *  The trace is derived from this and not from the number, so inserting a node or moving
   *  one no longer changes anybody's answers and no table has to be kept in step. */
  key: string;
  code: string;
  title: string;
  target: string;
  access: "TRAINEE" | "INFILTRATOR" | "FIELD OPERATOR" | "OPERATOR";
  sceneLabel: string;
  narrative: string;
  actionLabel?: string;
  /** A single suggestive line the operator may choose to open. It points at the layer that
   *  holds the trace without naming the tool: being told the answer is not the game. */
  intel: string;
  /** The stamp the node leaves once its instrument has reported. Everything else the node
   *  shows lives in that instrument, because each node is operated differently. */
  scan: { verdict: string };
  /** Shown only after the node is cleared. Why the thing just found is a defect, and what a
   *  report would recommend. Withheld until then so it never doubles as a hint. */
  lesson: { risk: string; fix: string };
  surface:
    | "tooltip" | "comment" | "field" | "identity" | "invisible-ink" | "template-tag" | "shadow-root"
    | "cookie" | "local-memory" | "until-you-leave" | "deeper-store"
    | "route" | "robots" | "sitemap" | "source-map"
    | "response" | "redirect" | "header" | "console" | "request" | "cipher" | "range" | "render" | "query" | "vault";
};

export const blackTraceStages: BlackTraceStage[] = [
  {
    id: 1,
    key: "tooltip",
    code: "CASE #001",
    title: "Idle Tooltip",
    target: "intake-desk.lab",
    access: "TRAINEE",
    sceneLabel: "LABEL LAYER: PRESENT",
    actionLabel: "READ LABEL",
    narrative: "접수 단말기부터 잡는다. 겉에 걸린 것은 안내 문구뿐이지만, 이런 화면은 만든 사람의 메모를 그대로 달고 다닌다.",
    intel: "화면에 나온 글자가 그 요소가 가진 글자의 전부는 아니다.",
    scan: { verdict: "LABEL TRUNCATED" },
    lesson: { risk: "설명이나 안내를 담는 속성에 내부 메모를 적어 두는 일이 흔하다. 화면이 줄여서 보여줄 뿐 값은 그대로 전달된다.", fix: "사용자에게 보일 문구만 넣고, 담당자 메모나 내부 코드는 넣지 않는다." },
    surface: "tooltip",
  },
  {
    id: 2,
    key: "wrong-destination",
    code: "CASE #002",
    title: "Wrong Destination",
    target: "relay-gateway.lab",
    access: "TRAINEE",
    sceneLabel: "ROUTE: FORWARDED",
    actionLabel: "CONTINUE",
    narrative: "중계 관문을 통과한다. 통과 자체는 막히지 않는다. 이 관문이 무엇을 같이 들고 넘어가는지가 문제다.",
    intel: "도착하고 나서도 지나온 경로는 어딘가에 적혀 남는다.",
    scan: { verdict: "ROUTE FORWARDED" },
    lesson: { risk: "URL은 브라우저 기록, 서버 접근 로그, Referer 헤더에 동시에 남는다. 토큰이나 개인정보를 쿼리에 실으면 세 곳에 한 번에 기록된다.", fix: "민감한 값은 쿼리가 아니라 본문으로 보내고, 외부로 나가는 Referer를 제한한다." },
    surface: "route",
  },
  {
    id: 3,
    key: "ghost-comment",
    code: "CASE #003",
    title: "Ghost Comment",
    target: "recon-terminal.lab",
    access: "TRAINEE",
    sceneLabel: "SURFACE STATUS: QUIET",
    actionLabel: "INSPECT RECORD",
    narrative: "정찰 단말을 장악했다. 운영자가 기록을 지웠지만, 지우는 쪽은 언제나 눈에 보이는 것부터 지운다.",
    intel: "화면에 그려진 것이 서버가 보낸 전부는 아니다.",
    scan: { verdict: "RECORD EMPTY" },
    lesson: { risk: "개발 중 남긴 주석이 운영 빌드에 그대로 올라가면 내부 경로, 임시 계정, 처리 로직이 소스 보기만으로 드러난다. 공격자는 코드를 읽는 것이 아니라 주석을 읽는다.", fix: "배포 빌드에서 주석을 제거하고, 민감한 메모는 소스가 아니라 이슈 트래커에 남긴다." },
    surface: "comment",
  },
  {
    id: 4,
    key: "forgotten-field",
    code: "CASE #004",
    title: "Forgotten Field",
    target: "auth-terminal.lab",
    access: "TRAINEE",
    sceneLabel: "FORM LAYER: SEALED",
    actionLabel: "AUTHENTICATE",
    narrative: "폐기 처리된 인증 단말이다. 화면으로는 한 글자도 넣을 수 없다. 그런데 이 단말은 아직 무언가를 전송하고 있다.",
    intel: "보내는 칸의 수와 보이는 칸의 수가 같으리라는 법은 없다.",
    scan: { verdict: "AUTH REJECTED" },
    lesson: { risk: "숨은 입력칸은 사용자가 고칠 수 있다. 값이 HTML에 적혀 있지 않아도 스크립트가 채워 넣은 뒤 그대로 전송되므로, 가격이나 권한이나 식별자를 여기에 담으면 조작된 값이 서버에 도달한다.", fix: "화면에서 숨겼다는 것은 통제가 아니다. 값은 서버가 세션 기준으로 다시 판단한다." },
    surface: "field",
  },
  {
    id: 5,
    key: "embedded-identity",
    code: "CASE #005",
    title: "Embedded Identity",
    target: "personnel-archive.lab",
    access: "TRAINEE",
    sceneLabel: "IDENTITY MAP: PARTIAL",
    actionLabel: "READ CARD",
    narrative: "인사 기록고에 붙었다. 쥐고 있는 출입 카드는 이미 정지된 것인데, 이 시스템은 여전히 이 카드를 다른 카드와 구분한다.",
    intel: "인쇄된 면이 카드의 전부는 아니다.",
    scan: { verdict: "IDENTITY REDACTED" },
    lesson: { risk: "DOM 속성은 누구나 읽는다. 내부 식별자나 권한 정보를 붙여 두면 목록 화면 한 번으로 전량 수집된다.", fix: "화면이 실제로 쓰는 값만 내려보내고, 내부 식별자는 서버에서만 다룬다." },
    surface: "identity",
  },
  {
    id: 6,
    key: "invisible-ink",
    code: "CASE #006",
    title: "Invisible Ink",
    target: "archive-viewer.lab",
    access: "TRAINEE",
    sceneLabel: "RENDER LAYER: PARTIAL",
    actionLabel: "RENDER DOCUMENT",
    narrative: "열람실 단말을 잡았다. 요청한 문서는 전부 내려왔다. 화면이 그중 일부만 그리기로 했을 뿐이다.",
    intel: "그리지 않기로 한 것과 보내지 않은 것은 다르다.",
    scan: { verdict: "BLOCK NOT PAINTED" },
    lesson: { risk: "화면에서 감추는 처리는 전달을 막지 못한다. 권한이 없는 항목을 숨기기만 하면 내용은 그대로 내려가 있다.", fix: "볼 수 없는 항목은 아예 내려보내지 않는다. 감추기는 화면 정리이지 접근 통제가 아니다." },
    surface: "invisible-ink",
  },
  {
    id: 7,
    key: "template-tag",
    code: "CASE #007",
    title: "Unrendered Block",
    target: "render-queue.lab",
    access: "TRAINEE",
    sceneLabel: "TEMPLATE: STANDBY",
    actionLabel: "INSPECT QUEUE",
    narrative: "렌더 대기열에 들어왔다. 조건이 맞는 사용자에게만 보여줄 조각들이 이미 전부 내려와 쌓여 있다.",
    intel: "아직 자리를 잡지 않은 것이 아직 오지 않은 것은 아니다.",
    scan: { verdict: "TEMPLATE NOT INSTANTIATED" },
    lesson: { risk: "조건부로 보여줄 화면 조각을 미리 내려보내면, 조건을 만족하지 못한 사용자도 그 내용을 전부 가지고 있게 된다.", fix: "권한이나 조건에 따라 달라지는 화면 조각은 서버가 그때 내려보낸다." },
    surface: "template-tag",
  },
  {
    id: 8,
    key: "shadow-root",
    code: "CASE #008",
    title: "Shadow Root",
    target: "widget-host.lab",
    access: "TRAINEE",
    sceneLabel: "SHADOW TREE: ATTACHED",
    actionLabel: "OPEN COMPONENT",
    narrative: "이 구역의 부품 하나가 평범한 조회에 걸리지 않는다. 자기 안쪽 문서를 따로 들고 다니기 때문이다.",
    intel: "문서는 하나가 아니다. 어떤 부품은 자기 안쪽 문서를 따로 들고 다닌다.",
    scan: { verdict: "SHADOW TREE SEALED" },
    lesson: { risk: "구성요소 안쪽은 바깥 검색에 걸리지 않을 뿐 숨겨진 것이 아니다. 캡슐화를 보안 경계로 쓰면 그 안의 값이 그대로 노출된다.", fix: "캡슐화는 코드 구조이지 접근 통제가 아니다. 민감한 값은 어느 쪽에도 두지 않는다." },
    surface: "shadow-root",
  },
  {
    id: 9,
    key: "residual-trace",
    code: "CASE #009",
    title: "Residual Trace",
    target: "session-monitor.lab",
    access: "TRAINEE",
    sceneLabel: "LOCAL TRACE: DETECTED",
    actionLabel: "CHECK SESSION",
    narrative: "직전 운영자가 세션을 닫고 나갔다. 나간 자리를 그대로 두고 가는 운영자는 생각보다 많다.",
    intel: "브라우저는 사이트마다 따로 기억해 둔다.",
    scan: { verdict: "SESSION ENDED" },
    lesson: { risk: "쿠키는 브라우저에 평문으로 남고 스크립트가 읽을 수 있다. 세션이나 개인정보를 그대로 담으면 XSS 한 번에 전부 새어 나간다.", fix: "세션 쿠키에 HttpOnly·Secure·SameSite를 적용하고, 식별자 외의 값은 담지 않는다." },
    surface: "cookie",
  },
  {
    id: 10,
    key: "local-memory",
    code: "CASE #010",
    title: "Local Memory",
    target: "profile-cache.lab",
    access: "TRAINEE",
    sceneLabel: "PERSISTENT STORE: WARM",
    actionLabel: "READ CACHE",
    narrative: "이 단말은 같은 사용자를 여러 번 맞이했다. 다시 묻지 않으려고 적어 둔 것이 아직 그대로 있다.",
    intel: "다시 묻지 않으려면 어딘가에 적어 두어야 한다. 그 자리는 탭을 닫아도 남는다.",
    scan: { verdict: "CACHE RETAINED" },
    lesson: { risk: "브라우저 저장소는 평문이고 스크립트가 전부 읽는다. 토큰이나 개인정보를 두면 XSS 한 번에 영구 저장된 값까지 함께 나간다.", fix: "인증 정보는 저장소가 아니라 HttpOnly 쿠키로 다루고, 저장소에는 복구 가능한 설정값만 둔다." },
    surface: "local-memory",
  },
  {
    id: 11,
    key: "until-you-leave",
    code: "CASE #011",
    title: "Until You Leave",
    target: "session-cache.lab",
    access: "TRAINEE",
    sceneLabel: "VOLATILE STORE: HOT",
    actionLabel: "READ SESSION",
    narrative: "탭이 닫히면 사라질 값이다. 다행히 이 탭은 아직 열려 있다.",
    intel: "탭이 살아 있는 동안만 남는 자리도 있다.",
    scan: { verdict: "SESSION VALUE LIVE" },
    lesson: { risk: "휘발성이라는 이유로 민감한 값을 두는 경우가 많지만, 세션이 살아 있는 동안에는 스크립트가 언제든 읽는다.", fix: "휘발성은 보호가 아니다. 저장 위치가 아니라 값의 성격으로 판단한다." },
    surface: "until-you-leave",
  },
  {
    id: 12,
    key: "deeper-store",
    code: "CASE #012",
    title: "Deeper Store",
    target: "offline-db.lab",
    access: "TRAINEE",
    sceneLabel: "OBJECT STORE: OPEN",
    actionLabel: "QUERY DATABASE",
    narrative: "이 서비스는 연결이 끊겨도 돌아가려고 자체 데이터베이스를 들고 있다. 그 안에 업무 기록이 그대로 들어 있다.",
    intel: "브라우저가 가진 저장 수단은 열쇠-값 한 쌍이 전부가 아니다.",
    scan: { verdict: "RECORD FOUND" },
    lesson: { risk: "오프라인 캐시에 업무 데이터를 담으면 단말기를 잃는 순간 그 데이터도 함께 간다. 로그아웃해도 지워지지 않는 경우가 많다.", fix: "오프라인 저장 대상은 최소화하고, 로그아웃 시 삭제 절차를 반드시 둔다." },
    surface: "deeper-store",
  },
  {
    id: 13,
    key: "robot-rules",
    code: "CASE #013",
    title: "Robot Rules",
    target: "security-index.lab",
    access: "INFILTRATOR",
    sceneLabel: "AUTOMATION: WATCHING",
    actionLabel: "PING CRAWLER",
    narrative: "이 서버를 찾아오는 쪽은 사람만이 아니다. 자동 수집기에게 먼저 건네는 안내가 따로 있다.",
    intel: "그 안내문은 사람이 읽으라고 둔 자리에 있지 않다.",
    scan: { verdict: "POLICY NOT RENDERED" },
    lesson: { risk: "robots.txt는 숨기는 장치가 아니라 공개 문서다. 숨기고 싶은 경로를 적는 순간 그 경로를 광고하게 된다.", fix: "접근 통제는 인증과 권한으로 한다. robots.txt에 비공개 경로를 적지 않는다." },
    surface: "robots",
  },
  {
    id: 14,
    key: "sitemap",
    code: "CASE #014",
    title: "Index of Everything",
    target: "search-index.lab",
    access: "INFILTRATOR",
    sceneLabel: "INDEX FILE: SERVED",
    actionLabel: "FETCH INDEX",
    narrative: "검색 노출용 목록을 받아 왔다. 화면 어디에서도 연결되지 않은 주소가 거기 섞여 있다.",
    intel: "안내용으로 만든 목록이 가장 성실한 안내서가 되기도 한다.",
    scan: { verdict: "ORPHAN PATH LISTED" },
    lesson: { risk: "검색 노출용 목록에 관리 화면이나 시험용 경로가 섞여 들어가면, 링크가 없어 못 찾던 주소가 한 번에 공개된다.", fix: "목록은 공개해도 되는 경로만 담아 생성하고, 생성 결과를 배포 전에 검토한다." },
    surface: "sitemap",
  },
  {
    id: 15,
    key: "source-map",
    code: "CASE #015",
    title: "Before the Build",
    target: "build-output.lab",
    access: "INFILTRATOR",
    sceneLabel: "SOURCE MAP: AVAILABLE",
    actionLabel: "TRACE BUILD",
    narrative: "배포된 스크립트는 알아보기 어렵게 압축되어 있다. 그런데 압축을 되돌릴 안내서가 같은 자리에 함께 올라와 있다.",
    intel: "압축된 코드를 되돌려 읽는 쪽은 사람만이 아니다. 그 안내서도 같이 배포된다.",
    scan: { verdict: "ORIGINAL SOURCE RECOVERED" },
    lesson: { risk: "소스 맵이 운영에 올라가면 압축은 아무 의미가 없다. 주석, 변수명, 내부 경로가 담긴 원본이 그대로 복원된다.", fix: "운영 빌드에서는 소스 맵을 배포하지 않거나, 접근을 사내로 제한한다." },
    surface: "source-map",
  },
  {
    id: 16,
    key: "silent-response",
    code: "CASE #016",
    title: "Silent Response",
    target: "remote-node.lab",
    access: "INFILTRATOR",
    sceneLabel: "CONNECTION: WAITING",
    actionLabel: "CONNECT",
    narrative: "폐쇄된 줄 알았던 노드가 응답한다. 화면에는 아무것도 뜨지 않는데, 회선에는 분명히 무언가 지나갔다.",
    intel: "실패한 것처럼 보여도 주고받은 것은 이미 있다.",
    scan: { verdict: "CONNECTION FAILED" },
    lesson: { risk: "화면이 쓰지 않는 필드까지 응답에 담기면, 보이지 않는다는 이유로 안전하다고 착각하게 된다. 응답 본문은 그대로 열람된다.", fix: "응답은 화면이 실제로 쓰는 필드만 구성한다. 모델 전체를 그대로 직렬화하지 않는다." },
    surface: "response",
  },
  {
    id: 17,
    key: "server-whisper",
    code: "CASE #017",
    title: "Server Whisper",
    target: "comms-node.lab",
    access: "INFILTRATOR",
    sceneLabel: "STATUS: ONLINE",
    actionLabel: "REQUEST STATUS",
    narrative: "통신 노드는 정상이다. 회선은 계속 살아 있는데 넘어오는 내용만 비어 있다.",
    intel: "본문이 비었다고 응답까지 빈 것은 아니다.",
    scan: { verdict: "BODY EMPTY" },
    lesson: { risk: "커스텀 헤더는 화면에 보이지 않지만 응답을 열면 그대로 보인다. 디버그용 헤더가 운영에 남는 사고는 흔하다.", fix: "운영 응답에서 디버그·내부 헤더를 제거하고, 서버와 프레임워크 버전 노출도 함께 줄인다." },
    surface: "header",
  },
  {
    id: 18,
    key: "follow-the-trail",
    code: "CASE #018",
    title: "Follow the Trail",
    target: "personnel-trace.lab",
    access: "INFILTRATOR",
    sceneLabel: "REDIRECT: CAPTURED",
    actionLabel: "TRACE MOVEMENT",
    narrative: "대상은 작전 직전에 구역을 옮겼다. 도착지에는 아무것도 없다. 길을 알려준 쪽이 따로 있다.",
    intel: "길을 알려준 쪽과 도착한 쪽은 서로 다른 응답이다.",
    scan: { verdict: "RECORD NOT FOUND" },
    lesson: { risk: "리다이렉트 응답의 Location에 값을 실으면 최종 화면이 아니라 중간 응답에 그것이 남는다. 중간 응답은 접근 로그와 브라우저 기록에 그대로 쌓인다.", fix: "인증 값을 URL로 넘기지 않는다. 넘겨야 한다면 일회용 단기 토큰으로 제한한다." },
    surface: "redirect",
  },
  {
    id: 19,
    key: "ask-it-yourself",
    code: "CASE #019",
    title: "Ask It Yourself",
    target: "relay-gate.lab",
    access: "INFILTRATOR",
    sceneLabel: "PANEL: READ ONLY",
    actionLabel: "COPY ADDRESS",
    narrative: "여기까지는 화면이 대신 요청을 보내 주었다. 이 화면은 주소까지만 알려 주고 보내지는 않는다.",
    intel: "돌아온 답을 어디서 읽어야 하는지는 앞에서 한 번 해 봤다.",
    scan: { verdict: "NO REQUEST SENT" },
    lesson: { risk: "요청을 직접 만들 수 있는 사람은 화면이 허용한 것만 보내지 않는다. 비활성화한 버튼, 숨긴 입력, 화면에서 막아 둔 값은 통제가 아니다.", fix: "모든 검증은 서버에서 한다. 화면이 보내지 않는다는 사실에 기대어 설계하지 않는다." },
    surface: "console",
  },
  {
    id: 20,
    key: "wrong-method",
    code: "CASE #020",
    title: "Wrong Verb",
    target: "intake-api.lab",
    access: "INFILTRATOR",
    sceneLabel: "METHOD: REFUSED",
    actionLabel: "SEND REQUEST",
    narrative: "접수 창구는 열려 있는데 문을 두드리는 방식이 틀렸다. 같은 주소가 다른 방식에는 다르게 답한다.",
    intel: "주소 하나가 방식 하나만 받는 것은 아니다.",
    scan: { verdict: "METHOD NOT ALLOWED" },
    lesson: { risk: "읽기 전용으로 알려진 주소가 다른 메서드에는 전혀 다르게 응답하는 경우가 있다. 점검 범위를 메서드 단위로 넓히지 않으면 통째로 빠진다.", fix: "허용 메서드를 명시적으로 제한하고, 허용하지 않는 메서드는 처리 전에 거절한다." },
    surface: "request",
  },
  {
    id: 21,
    key: "cookie-flags",
    code: "CASE #021",
    title: "Flags on the Cookie",
    target: "session-issuer.lab",
    access: "INFILTRATOR",
    sceneLabel: "SET-COOKIE: OBSERVED",
    actionLabel: "REQUEST SESSION",
    narrative: "창구가 세션을 하나 발급한다. 값 자체는 평범한데, 그 값에 함께 붙어 나오는 설정이 평범하지 않다.",
    intel: "쿠키는 값만으로 이루어져 있지 않다.",
    scan: { verdict: "COOKIE ATTRIBUTES EXPOSED" },
    lesson: { risk: "쿠키의 보호 설정은 값과 함께 응답에 그대로 적혀 나온다. HttpOnly나 Secure가 빠진 세션은 발급 순간에 드러난다.", fix: "세션 쿠키에 HttpOnly·Secure·SameSite를 빠짐없이 지정하고, 발급 응답을 점검 항목에 포함한다." },
    surface: "request",
  },
  {
    id: 22,
    key: "claimed-role",
    code: "CASE #022",
    title: "Who Is Asking",
    target: "content-gate.lab",
    access: "INFILTRATOR",
    sceneLabel: "ROLE CHECK: ACTIVE",
    actionLabel: "SEND REQUEST",
    narrative: "이 관문은 찾아온 쪽이 자기를 뭐라고 밝히는지 보고 답을 바꾼다. 밝히는 쪽은 서버가 아니다.",
    intel: "서버는 확인하지 않는다. 요청이 스스로 밝힌 말을 믿을 뿐이다.",
    scan: { verdict: "ROLE ACCEPTED AS CLAIMED" },
    lesson: { risk: "요청 헤더로 권한을 판단하는 통제는 그 헤더를 직접 적어 보내면 그대로 넘어간다. 관리 기능을 이렇게 가르는 사례가 흔하다.", fix: "클라이언트가 보낸 값은 식별이 아니라 참고 정보다. 권한은 세션으로 판단한다." },
    surface: "request",
  },
  {
    id: 23,
    key: "referer",
    code: "CASE #023",
    title: "Where You Came From",
    target: "partner-portal.lab",
    access: "INFILTRATOR",
    sceneLabel: "ORIGIN CHECK: ACTIVE",
    actionLabel: "SEND REQUEST",
    narrative: "제휴 포털은 내부 화면에서 넘어온 요청만 받는다. 어디서 왔는지는 요청에 적혀 있다.",
    intel: "어디서 왔는지를 적는 쪽은 서버가 아니다.",
    scan: { verdict: "ORIGIN HEADER TRUSTED" },
    lesson: { risk: "출처 헤더로 접근을 가르는 통제는 헤더를 직접 적어 보내면 무력화된다. 결제나 다운로드 경로에서 자주 발견된다.", fix: "출처 헤더는 통계용으로만 쓰고, 접근 판단은 세션과 서버 측 토큰으로 한다." },
    surface: "request",
  },
  {
    id: 24,
    key: "etag",
    code: "CASE #024",
    title: "The Tag Remembered",
    target: "asset-cache.lab",
    access: "INFILTRATOR",
    sceneLabel: "VALIDATOR: PRESENT",
    actionLabel: "REQUEST ASSET",
    narrative: "같은 파일을 두 번 요청하면 서버는 두 번째에 본문을 보내지 않는다. 대신 그것이 같은 파일임을 알아보는 표를 쓴다.",
    intel: "서버가 본문을 아낄 때 쓰는 표에도 내용이 담긴다.",
    scan: { verdict: "VALIDATOR LEAKS CONTENT" },
    lesson: { risk: "캐시 검증용 값에 파일 내용의 해시나 내부 버전, 경로가 담기는 구현이 있다. 본문을 받지 않고도 내부 구조를 추정할 수 있다.", fix: "검증 값은 내용과 무관한 난수나 불투명한 버전으로 만든다." },
    surface: "request",
  },
  {
    id: 25,
    key: "range",
    code: "CASE #025",
    title: "Ask for a Piece",
    target: "archive-store.lab",
    access: "INFILTRATOR",
    sceneLabel: "RANGE: SUPPORTED",
    actionLabel: "REQUEST PART",
    narrative: "보관소는 큰 파일을 통째로만 내주지 않는다. 몇 번째 바이트부터 몇 번째까지인지 말하면 그 부분만 보낸다.",
    intel: "전부 달라고만 할 필요는 없다.",
    scan: { verdict: "PARTIAL CONTENT SERVED" },
    lesson: { risk: "부분 요청을 허용하면 접근 통제가 전체 다운로드만 검사하는 구현에서 조각을 모아 우회할 수 있다.", fix: "부분 요청에도 동일한 권한 검사를 적용하고, 범위 값의 유효성을 검증한다." },
    surface: "request",
  },
  {
    id: 26,
    key: "preflight",
    code: "CASE #026",
    title: "The Question Before",
    target: "cross-origin.lab",
    access: "INFILTRATOR",
    sceneLabel: "PREFLIGHT: ANSWERED",
    actionLabel: "SEND PREFLIGHT",
    narrative: "브라우저는 본 요청을 보내기 전에 먼저 묻는다. 그 물음에 대한 답에도 서버의 사정이 적혀 있다.",
    intel: "본 요청 전에 오가는 대화가 따로 있다.",
    scan: { verdict: "PREFLIGHT DISCLOSES POLICY" },
    lesson: { risk: "사전 요청 응답에는 허용 메서드와 허용 헤더가 모두 적힌다. 공개되지 않은 기능의 존재가 여기서 드러난다.", fix: "허용 목록을 필요한 범위로 좁히고, 사전 요청 응답에 내부 전용 항목을 싣지 않는다." },
    surface: "request",
  },
  {
    id: 27,
    key: "status-only",
    code: "CASE #027",
    title: "No Body, Still Speaks",
    target: "ack-node.lab",
    access: "INFILTRATOR",
    sceneLabel: "STATUS: 204",
    actionLabel: "SEND ACK",
    narrative: "이 노드는 본문을 보내지 않는다. 상태 줄 하나로 끝낸다. 그렇다고 아무것도 보내지 않은 것은 아니다.",
    intel: "본문이 없다는 것과 응답이 없다는 것은 다르다.",
    scan: { verdict: "EMPTY BODY RESPONSE" },
    lesson: { risk: "본문이 없는 응답은 점검에서 건너뛰기 쉽다. 헤더만으로 정보를 전달하는 구현이 그 틈에 남는다.", fix: "본문 유무와 무관하게 응답 전체를 점검 대상으로 둔다." },
    surface: "request",
  },
  {
    id: 28,
    key: "content-type",
    code: "CASE #028",
    title: "Served as the Wrong Thing",
    target: "report-export.lab",
    access: "INFILTRATOR",
    sceneLabel: "CONTENT TYPE: MISMATCH",
    actionLabel: "FETCH EXPORT",
    narrative: "내려받은 파일이 화면에 제대로 열리지 않는다. 내용이 잘못된 것이 아니라, 서버가 종류를 잘못 적어 보냈다.",
    intel: "브라우저가 못 여는 것과 내용이 없는 것은 다르다.",
    scan: { verdict: "TYPE MISDECLARED" },
    lesson: { risk: "응답 종류를 잘못 적으면 브라우저가 내용을 그대로 글자로 펼친다. 반대로 사용자 입력이 섞인 응답이 문서로 선언되면 스크립트가 실행된다.", fix: "응답 종류를 내용에 맞게 지정하고, X-Content-Type-Options로 추측을 막는다." },
    surface: "request",
  },
  {
    id: 29,
    key: "two-requests",
    code: "CASE #029",
    title: "The First Answer Was a Map",
    target: "dispatch-node.lab",
    access: "INFILTRATOR",
    sceneLabel: "HANDOFF: STAGED",
    actionLabel: "OPEN DISPATCH",
    narrative: "배차 노드는 한 번에 답하지 않는다. 첫 응답은 다음에 어디로 물어야 하는지를 알려줄 뿐이다.",
    intel: "응답 하나가 끝이 아닐 수도 있다.",
    scan: { verdict: "HANDOFF REQUIRED" },
    lesson: { risk: "여러 단계로 나뉜 흐름은 각 단계가 따로 점검되면서 전체 연결이 빠진다. 중간 단계만 통과하면 끝까지 가는 구현이 남는다.", fix: "흐름 전체를 하나의 권한 경계로 보고, 각 단계에서 동일한 검사를 반복한다." },
    surface: "request",
  },
  {
    id: 30,
    key: "plain-sight",
    code: "CASE #030",
    title: "Plain Sight",
    target: "config-store.lab",
    access: "FIELD OPERATOR",
    sceneLabel: "PAYLOAD: ENCODED",
    actionLabel: "READ VALUE",
    narrative: "설정 저장소에서 값을 하나 꺼냈다. 글자가 뒤섞여 있어 그대로는 쓸 수 없다.",
    intel: "읽을 수 없다는 것과 잠겨 있다는 것은 다르다.",
    scan: { verdict: "VALUE ENCODED NOT ENCRYPTED" },
    lesson: { risk: "인코딩을 보호로 오해해 자격 증명이나 설정값을 그대로 담는 사례가 많다. 되돌리는 데 열쇠가 필요 없다.", fix: "인코딩은 전송 형식이지 보호가 아니다. 보호가 필요하면 암호화하고 열쇠를 분리한다." },
    surface: "cipher",
  },
  {
    id: 31,
    key: "bytes-as-text",
    code: "CASE #031",
    title: "Bytes as Text",
    target: "memory-dump.lab",
    access: "FIELD OPERATOR",
    sceneLabel: "FORMAT: HEX",
    actionLabel: "READ DUMP",
    narrative: "메모리 덤프 한 조각이다. 숫자와 알파벳 앞쪽 글자만 쓰인 것이 눈에 띈다.",
    intel: "쓰인 글자의 종류가 형식을 말해 준다.",
    scan: { verdict: "BYTE SEQUENCE CAPTURED" },
    lesson: { risk: "덤프나 로그에 바이트 그대로 남은 값은 형식만 되돌리면 원문이 된다. 사람이 읽기 어렵다는 이유로 마스킹을 생략하는 경우가 많다.", fix: "저장 전에 민감한 값을 제거하고, 덤프 산출물 자체를 접근 통제 대상으로 둔다." },
    surface: "cipher",
  },
  {
    id: 32,
    key: "percent-signs",
    code: "CASE #032",
    title: "Percent Signs",
    target: "query-log.lab",
    access: "FIELD OPERATOR",
    sceneLabel: "FORMAT: ESCAPED",
    actionLabel: "READ ENTRY",
    narrative: "접근 로그 한 줄이다. 주소에 실려 넘어간 값이 그대로 기록되어 있고, 특수 문자만 자리를 바꿔 적혀 있다.",
    intel: "주소에 실리는 값은 자리를 바꿔 적힌다.",
    scan: { verdict: "LOG ENTRY RETAINED" },
    lesson: { risk: "주소에 실린 값은 접근 로그에 그대로 쌓인다. 로그는 보통 더 많은 사람이 볼 수 있다.", fix: "민감한 값을 주소에 싣지 않고, 로그 적재 전에 질의 문자열을 정리한다." },
    surface: "cipher",
  },
  {
    id: 33,
    key: "shifted",
    code: "CASE #033",
    title: "Shifted",
    target: "notes-archive.lab",
    access: "FIELD OPERATOR",
    sceneLabel: "CIPHER: CLASSICAL",
    actionLabel: "READ NOTE",
    narrative: "운영자 메모다. 글자 수와 모양은 멀쩡한데 단어가 되지 않는다. 자리만 밀려 있다.",
    intel: "글자가 바뀐 것이 아니라 자리가 밀렸을 뿐일 수도 있다.",
    scan: { verdict: "SUBSTITUTION DETECTED" },
    lesson: { risk: "자리를 미는 방식은 난독화이지 암호가 아니다. 내부 메모나 쿠폰 코드에 아직 쓰인다.", fix: "비밀 유지가 목적이면 검증된 암호를 쓴다. 난독화는 열람을 늦출 뿐 막지 못한다." },
    surface: "cipher",
  },
  {
    id: 34,
    key: "one-byte-key",
    code: "CASE #034",
    title: "One Byte Key",
    target: "firmware-blob.lab",
    access: "FIELD OPERATOR",
    sceneLabel: "CIPHER: REPEATING",
    actionLabel: "READ BLOB",
    narrative: "펌웨어 조각이다. 바이트가 고르게 흩어져 있지 않고, 같은 간격으로 같은 흔적이 반복된다.",
    intel: "모든 글자가 같은 방식으로 틀어졌다면, 틀어 놓은 것은 하나뿐이다.",
    scan: { verdict: "WEAK OBFUSCATION" },
    lesson: { risk: "한 바이트로 전체를 뒤집는 방식은 알려진 앞머리 몇 글자만으로 되돌릴 수 있다. 기기 펌웨어와 설정 파일에 흔하다.", fix: "열쇠 하나로 반복 적용하는 방식을 쓰지 않는다. 표준 암호와 키 관리 체계를 쓴다." },
    surface: "cipher",
  },
  {
    id: 35,
    key: "two-alphabets",
    code: "CASE #035",
    title: "Two Alphabets",
    target: "token-store.lab",
    access: "FIELD OPERATOR",
    sceneLabel: "ALPHABET: VARIANT",
    actionLabel: "READ TOKEN",
    narrative: "토큰 저장소의 값이다. 포장 방식은 익숙한데, 쓰인 글자 중 둘이 평소와 다르다.",
    intel: "같은 포장에도 쓰이는 글자가 두 가지다.",
    scan: { verdict: "ALPHABET MISMATCH" },
    lesson: { risk: "주소에 안전하게 싣기 위한 변형 알파벳을 모르면 복호가 실패하고, 점검자가 값을 해석 불가로 넘겨 버린다.", fix: "토큰 형식을 문서에 명시하고, 점검 절차에 변형 알파벳을 포함한다." },
    surface: "cipher",
  },
  {
    id: 36,
    key: "three-parts",
    code: "CASE #036",
    title: "Three Parts",
    target: "auth-issuer.lab",
    access: "FIELD OPERATOR",
    sceneLabel: "TOKEN: SIGNED",
    actionLabel: "READ TOKEN",
    narrative: "인증 서버가 발급한 토큰이다. 점으로 나뉜 세 조각이고, 서명이 붙어 있다.",
    intel: "서명이 붙어 있다는 것과 내용이 가려져 있다는 것은 다르다.",
    scan: { verdict: "CLAIMS READABLE" },
    lesson: { risk: "서명된 토큰의 내용은 누구나 읽는다. 서명은 위조를 막을 뿐 가리지 않는데, 내부 식별자나 권한을 담는 사례가 많다.", fix: "토큰에는 최소한의 식별자만 담고, 민감한 값은 서버가 보관한 뒤 참조만 전달한다." },
    surface: "cipher",
  },
  {
    id: 37,
    key: "no-signature",
    code: "CASE #037",
    title: "Where the Signature Should Be",
    target: "legacy-issuer.lab",
    access: "FIELD OPERATOR",
    sceneLabel: "TOKEN: UNSIGNED",
    actionLabel: "READ TOKEN",
    narrative: "구형 발급기가 만든 토큰이다. 형식은 같은데, 서명이 있어야 할 자리에 서명이 아닌 것이 들어 있다.",
    intel: "세 번째 조각이 늘 서명인 것은 아니다.",
    scan: { verdict: "SIGNATURE ABSENT" },
    lesson: { risk: "서명 방식을 토큰 자신이 선언하게 두면, 선언을 바꿔 서명 검사를 건너뛸 수 있다. 서명 자리에 엉뚱한 값이 남기도 한다.", fix: "허용 서명 방식을 서버가 고정하고, 토큰이 선언한 방식을 신뢰하지 않는다." },
    surface: "cipher",
  },
  {
    id: 38,
    key: "wrapped-twice",
    code: "CASE #038",
    title: "Wrapped Twice",
    target: "relay-queue.lab",
    access: "FIELD OPERATOR",
    sceneLabel: "LAYERS: 2",
    actionLabel: "READ MESSAGE",
    narrative: "중계 큐에 실린 메시지다. 한 겹을 벗겨 냈는데 아직 읽히지 않는다. 그 안에 또 한 겹이 있다.",
    intel: "한 번 벗겨서 읽히지 않으면 아직 끝이 아니다.",
    scan: { verdict: "NESTED ENCODING" },
    lesson: { risk: "여러 겹으로 감싼 값은 점검 도구가 한 겹만 보고 안전하다고 판정하기 쉽다. 탐지 우회에도 그대로 쓰인다.", fix: "입력 검증은 완전히 복호한 뒤의 값으로 수행한다." },
    surface: "cipher",
  },
  {
    id: 39,
    key: "layer-by-layer",
    code: "CASE #039",
    title: "Layer by Layer",
    target: "exfil-channel.lab",
    access: "FIELD OPERATOR",
    sceneLabel: "LAYERS: 3",
    actionLabel: "READ CAPTURE",
    narrative: "반출 채널에서 잡아낸 마지막 덩어리다. 겹이 여럿이고, 벗기는 순서가 정해져 있다.",
    intel: "겹마다 쓰인 방식이 같지 않다. 벗긴 뒤 남은 모양이 다음을 알려 준다.",
    scan: { verdict: "MULTI-LAYER PAYLOAD" },
    lesson: { risk: "여러 방식을 겹친 값은 단일 패턴을 찾는 탐지를 그대로 통과한다. 실제 반출 트래픽이 이 형태를 띤다.", fix: "탐지를 패턴 하나에 의존하지 않고, 복호 후 내용과 반출량을 함께 본다." },
    surface: "cipher",
  },
  {
    id: 40,
    key: "someone-elses-order",
    code: "CASE #040",
    title: "Someone Else's Order",
    target: "orders-api.lab",
    access: "OPERATOR",
    sceneLabel: "OWNERSHIP: UNCHECKED",
    actionLabel: "FETCH ORDER",
    narrative: "주문 조회 화면을 잡았다. 내 주문은 잘 나온다. 서버가 확인하는 것은 번호가 맞는지뿐이다.",
    intel: "번호가 맞는지와 그 번호가 당신 것인지는 다른 질문이다.",
    scan: { verdict: "OWNER NOT VERIFIED" },
    lesson: { risk: "식별자만 보고 돌려주는 조회는 번호를 바꾸는 것만으로 남의 자료를 꺼낸다. 진단에서 가장 자주 나오는 결함이고 자동 점검 도구는 잘 찾지 못한다.", fix: "조회할 때마다 그 자원이 요청자의 것인지 서버가 확인한다. 번호를 추측하기 어렵게 만드는 것은 보완책이지 통제가 아니다." },
    surface: "range",
  },
  {
    id: 41,
    key: "negative-quantity",
    code: "CASE #041",
    title: "Negative Quantity",
    target: "checkout-service.lab",
    access: "OPERATOR",
    sceneLabel: "INPUT: UNBOUNDED",
    actionLabel: "SUBMIT ORDER",
    narrative: "결제 단계다. 수량과 단가를 곱해 합계를 낸다. 수량이 얼마여야 하는지는 아무도 정해 두지 않았다.",
    intel: "값의 형식이 맞다는 것과 값이 말이 된다는 것은 다르다.",
    scan: { verdict: "TOTAL BELOW ZERO" },
    lesson: { risk: "범위를 정하지 않은 수량은 합계를 음수로 만들고 잔액을 늘린다. 형식 검증만 하는 입력 검사는 이것을 통과시킨다.", fix: "업무 규칙에 맞는 범위를 서버에서 강제하고, 금액은 서버가 다시 계산한다." },
    surface: "range",
  },
  {
    id: 42,
    key: "up-one-level",
    code: "CASE #042",
    title: "Up One Level",
    target: "docs-service.lab",
    access: "OPERATOR",
    sceneLabel: "PATH: JOINED",
    actionLabel: "FETCH DOCUMENT",
    narrative: "문서 열람 기능이다. 공개 폴더의 파일 이름을 넘기면 그 파일을 돌려준다. 넘긴 이름을 그대로 경로에 붙인다.",
    intel: "경로는 앞으로만 가지 않는다.",
    scan: { verdict: "PATH NOT NORMALIZED" },
    lesson: { risk: "사용자가 준 이름을 경로에 그대로 붙이면 공개 폴더 바깥의 파일이 열린다. 설정 파일과 자격 증명이 이렇게 나간다.", fix: "경로를 정규화한 뒤 허용된 디렉터리 안에 있는지 확인한다. 가능하면 이름 대신 식별자로 받는다." },
    surface: "range",
  },
  {
    id: 43,
    key: "role-in-the-token",
    code: "CASE #043",
    title: "Role in the Token",
    target: "range-issuer.lab",
    access: "OPERATOR",
    sceneLabel: "TOKEN: SELF-DESCRIBED",
    actionLabel: "REQUEST TOKEN",
    narrative: "모의 발급기가 토큰을 하나 내준다. 그 토큰에는 내가 무엇을 할 수 있는지가 적혀 있고, 검증하는 쪽은 적힌 대로 믿는다.",
    intel: "토큰은 자기가 어떻게 검사되어야 하는지까지 스스로 적어 둔다.",
    scan: { verdict: "CLAIMS TRUSTED AS GIVEN" },
    lesson: { risk: "서명 방식을 토큰이 선언하게 두면 선언을 바꿔 검사를 건너뛸 수 있다. 권한이 토큰 안에 적혀 있으면 그대로 올라간다.", fix: "허용 서명 방식을 서버가 고정하고 토큰의 선언을 무시한다. 권한은 토큰이 아니라 서버가 보관한 기록으로 판단한다." },
    surface: "range",
  },
  {
    id: 44,
    key: "twice-at-once",
    code: "CASE #044",
    title: "Twice at Once",
    target: "coupon-service.lab",
    access: "OPERATOR",
    sceneLabel: "CHECK: NOT ATOMIC",
    actionLabel: "APPLY COUPON",
    narrative: "쿠폰은 한 번만 쓸 수 있다. 서버는 쓴 적이 있는지 확인하고, 그 다음에 썼다고 기록한다. 두 동작 사이에 틈이 있다.",
    intel: "확인과 기록이 한 동작이 아니면, 그 사이에 다른 요청이 들어갈 수 있다.",
    scan: { verdict: "DOUBLE APPLY ACCEPTED" },
    lesson: { risk: "확인과 반영이 분리된 처리는 동시에 보낸 요청이 모두 확인을 통과한다. 쿠폰, 포인트, 잔액에서 금전 손실로 이어진다.", fix: "확인과 반영을 한 트랜잭션에서 처리하고, 고유 제약이나 원자적 갱신으로 중복을 막는다." },
    surface: "range",
  },
  {
    id: 45,
    key: "it-echoes-back",
    code: "CASE #045",
    title: "It Echoes Back",
    target: "search-service.lab",
    access: "OPERATOR",
    sceneLabel: "INPUT: REFLECTED",
    actionLabel: "SEARCH",
    narrative: "검색 기능이다. 넣은 말이 결과 화면에 그대로 다시 나온다. 서버는 그것을 글자로 보지 않는다.",
    intel: "되돌아온 것이 글자로만 남는지, 아니면 화면의 일부가 되는지가 갈림길이다.",
    scan: { verdict: "OUTPUT NOT ESCAPED" },
    lesson: { risk: "입력을 그대로 화면에 붙이면 공격자가 건넨 코드가 피해자의 브라우저에서 실행된다. 링크 한 번으로 세션이 넘어간다.", fix: "출력되는 위치에 맞는 변환을 적용한다. HTML 본문, 속성, 스크립트 안, 주소는 각각 규칙이 다르다. CSP로 인라인 실행을 함께 막는다." },
    surface: "render",
  },
  {
    id: 46,
    key: "it-stays-there",
    code: "CASE #046",
    title: "It Stays There",
    target: "board-service.lab",
    access: "OPERATOR",
    sceneLabel: "PAYLOAD: PERSISTED",
    actionLabel: "POST NOTE",
    narrative: "한 줄 메모를 남기면 게시판에 저장된다. 다음에 게시판을 열 때 그 메모가 다시 그려진다.",
    intel: "앞 노드는 링크를 건네야 했다. 여기서는 건넬 필요가 없다.",
    scan: { verdict: "STORED AND RENDERED" },
    lesson: { risk: "저장된 입력은 링크를 보내지 않아도 열람하는 모든 사람의 브라우저에서 실행된다. 관리자 화면에 심기면 그대로 권한 탈취로 이어진다.", fix: "저장할 때가 아니라 출력할 때 변환한다. 저장 시점만 거르면 우회 한 번에 저장된 전부가 살아난다." },
    surface: "render",
  },
  {
    id: 47,
    key: "always-true",
    code: "CASE #047",
    title: "Always True",
    target: "auth-service.lab",
    access: "OPERATOR",
    sceneLabel: "QUERY: CONCATENATED",
    actionLabel: "SIGN IN",
    narrative: "로그인 화면이다. 서버는 입력한 아이디와 비밀번호를 질의문에 그대로 이어 붙인다. 만들어진 질의문이 화면에 보인다.",
    intel: "조건이 하나라도 참이면 통과한다. 그 조건을 쓰는 쪽은 당신이다.",
    scan: { verdict: "CONDITION ALWAYS SATISFIED" },
    lesson: { risk: "입력을 질의문에 이어 붙이면 조건을 바꿔 인증을 건너뛸 수 있다. 비밀번호를 몰라도 들어간다.", fix: "매개변수 바인딩을 쓴다. 입력은 값으로만 전달되고 질의문의 구조가 되지 못한다. 따옴표를 거르는 방식은 우회 경로가 계속 나온다." },
    surface: "query",
  },
  {
    id: 48,
    key: "another-table",
    code: "CASE #048",
    title: "Another Table",
    target: "lookup-service.lab",
    access: "OPERATOR",
    sceneLabel: "RESULT SET: EXTENDABLE",
    actionLabel: "LOOK UP",
    narrative: "번호로 계정을 찾는 기능이다. 돌려주는 것은 이름과 역할 두 칸이다. 이 표 말고도 데이터베이스에는 다른 표가 있다.",
    intel: "결과 목록이 한 곳에서만 와야 할 이유는 없다. 칸 수만 맞으면 된다.",
    scan: { verdict: "RESULT SET EXTENDED" },
    lesson: { risk: "질의문 구조를 바꿀 수 있으면 원래 보여주려던 표 밖의 자료까지 같은 화면으로 끌어올 수 있다. 자격 증명과 개인정보가 이렇게 나간다.", fix: "바인딩이 먼저다. 더해서 응용프로그램 계정의 권한을 최소로 두면 뚫렸을 때 닿는 범위가 줄어든다." },
    surface: "query",
  },
  {
    id: 49,
    key: "yes-or-no",
    code: "CASE #049",
    title: "Yes or No",
    target: "probe-service.lab",
    access: "OPERATOR",
    sceneLabel: "RESPONSE: BOOLEAN",
    actionLabel: "PROBE",
    narrative: "이 기능은 자료를 돌려주지 않는다. 조건에 맞는 것이 있는지 없는지만 답한다.",
    intel: "한 번에 한 글자씩 물어볼 수 있다면, 보여 주지 않는 값도 끝내 다 알아낼 수 있다.",
    scan: { verdict: "ORACLE RESPONDS" },
    lesson: { risk: "내용을 돌려주지 않아도 참과 거짓만 갈리면 값을 한 글자씩 복원할 수 있다. 오류 메시지를 감추는 것은 대책이 아니라 시간 끌기다.", fix: "바인딩으로 구조 변경 자체를 막는다. 응답을 감추는 방식은 자동화 도구 앞에서 의미가 없다." },
    surface: "query",
  },
  {
    id: 50,
    key: "fragmented-key",
    code: "CASE #050",
    title: "Fragmented Key",
    target: "vault-node-01.lab",
    access: "OPERATOR",
    sceneLabel: "SIGNAL: FRAGMENTED",
    actionLabel: "RECOVER VAULT",
    narrative: "금고 노드다. MASTER ACCESS KEY는 둘로 쪼개져 있고, 두 조각이 같은 곳에 있지 않다.",
    intel: "한 조각은 이미 이 화면에 있다. 나머지는 물어봐야 온다.",
    scan: { verdict: "KEY INCOMPLETE" },
    lesson: { risk: "조각 하나하나는 사소해 보여도, 서로 다른 곳에서 모은 정보를 합치면 완전한 접근 수단이 된다. 진단에서 개별로는 '영향 없음'으로 넘긴 항목들이 묶여 사고가 된다.", fix: "노출 항목은 단독이 아니라 조합 기준으로 평가한다." },
    surface: "vault",
  },
];

/**
 * Stages whose trace the client itself plants in the browser (DOM, cookie, URL). Their value
 * must therefore be derived per operator on the server, or the single JavaScript bundle hands
 * every visitor the whole answer sheet. The remaining stages are issued by the trace channel.
 */
export const traceLabels: Record<string, string> = {
  tooltip: "the_label_said_more",
  "wrong-destination": "read_the_address",
  "ghost-comment": "ghost_in_the_source",
  "forgotten-field": "hidden_fields_remember",
  "embedded-identity": "attributes_tell_more",
  "invisible-ink": "sent_but_not_painted",
  "template-tag": "queued_never_drawn",
  "shadow-root": "a_tree_inside_a_tree",
  "residual-trace": "cookies_leave_traces",
  "local-memory": "it_waited_for_you",
  "until-you-leave": "only_while_open",
  "deeper-store": "a_database_in_here",
  "plain-sight": "encoding_is_not_a_lock",
  "bytes-as-text": "bytes_spelled_out",
  "percent-signs": "the_address_kept_it",
  shifted: "the_letters_only_moved",
  "one-byte-key": "one_byte_undid_it_all",
  "two-alphabets": "the_other_alphabet",
  "three-parts": "signed_is_not_hidden",
  "no-signature": "nothing_was_signed",
  "wrapped-twice": "one_more_layer",
  "layer-by-layer": "peel_in_order",
  "fragmented-key": "two_places",
};

/** Stage 10 is split in two: the browser holds part one, the trace channel answers with this. */
export const vaultTraceSuffix = "one_key}";

/**
 * Builds the trace planted in the browser for a stage. A null token reproduces the pre-rotation
 * value, which keeps the stages solvable while the learning function has no operator secret.
 */
export function composeTrace(key: string, token: string | null) {
  const label = traceLabels[key];
  if (!label) return null;
  const body = token ? `${label}_${token}` : label;
  return key === "fragmented-key" ? `FLAG{${body}_` : `FLAG{${body}}`;
}

/** The clearance ladder the operation advances through, used to show what the next node unlocks. */
/** Four tiers spread evenly across however many nodes the operation holds. Written as fixed
 *  numbers they had to be moved by hand every time a chapter was added, in two files that had to
 *  agree; derived from the count they move themselves. */
const tierNames = ["TRAINEE", "INFILTRATOR", "FIELD OPERATOR", "OPERATOR"] as const;

/**
 * The first node of each tier.
 *
 * These were four even quarters of the node count, which put two of the three promotions in the
 * middle of a chapter: an operator was told they had been promoted while still doing the same kind
 * of work, and once on the last node of a chapter. A promotion means a kind of work is finished, so
 * every boundary here is the first node of a chapter instead. A test asserts that, because the list
 * no longer derives itself and a reorder could otherwise quietly break the alignment.
 *
 *   TRAINEE         1-12  브라우저가 이미 가진 것을 읽는다 (Elements, Application)
 *   INFILTRATOR     13-29 서버와 주고받는 것을 다룬다 (주소창, Network, 요청 만들기)
 *   FIELD OPERATOR  30-39 실려 있는 값을 읽어낸다 (해독)
 *   OPERATOR        40-50 실제 결함을 다룬다 (연습장)
 */
export const blackTraceTierStarts = [1, 13, 30, 40] as const;

export function blackTraceTierFor(stage: number) {
  let tier = 0;
  for (let index = 1; index < tierNames.length; index += 1) {
    if (stage >= blackTraceTierStarts[index]) tier = index;
  }
  return tierNames[tier];
}

export const blackTraceRanks = tierNames.map((name, index) => ({
  at: blackTraceTierStarts[index],
  name,
}));

/** One number for the whole operation. It was written as a literal in eight places, which is how
 *  the certificate ended up requiring a node count the course no longer had. */
export const blackTraceNodeCount = blackTraceStages.length;

export function nextBlackTraceRank(currentStage: number) {
  return blackTraceRanks.find(rank => rank.at > currentStage) ?? null;
}

export const blackTraceStageById = (id: number) => blackTraceStages.find(stage => stage.id === id);
/** GUEST is reserved for a visitor without a session; a known stage always has a real tier. */
export const blackTraceAccessForStage = (stage: number) => blackTraceStageById(stage)?.access ?? "GUEST";
